version: "3.9"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gem-data:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - webpacker
      - postgres
      - redis
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker

  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - '127.0.0.1:3035:3035'

  postgres:
    image: postgres:13.2-alpine
    ports:
        - 5432:5432
    volumes:
        - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root

  pgadmin4:
    image: dpage/pgadmin4:5.0
    ports:
        - 8000:80
    volumes:
        - pgadmin4_volume:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: root
        PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres

  redis:
    hostname: redis
    image: redis:5.0.7
    ports:
      - 6379:6379

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:redis-commander-210
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379

volumes:
  gem-data:
  postgres_volume:
  pgadmin4_volume: