version: "3.9"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gem-data:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    ports:
        - 5432:5432
    volumes:
        - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root

  pgadmin4:
    image: dpage/pgadmin4:5.0
    ports:
        - 8000:80
    volumes:
        - pgadmin4_volume:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: root
        PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres

volumes:
  gem-data:
  postgres_volume:
  pgadmin4_volume: